### ISSUE TITLE
FUNGuild not working. Is the database there?

### ISSUE THREAD

**Issue by jorgeibarracaballero** [UMNFuN/FUNGuild#36]
Hello.
I am trying to use this program.
I downloaded and put in a folder in my home directory. Also downloaded the otu example table.
Then I tried this command, and got the error call that follows:

$ python Guilds_v1.1.py -otu ~/Downloads/otu_table_example.txt
Guilds_v1.1.py:92: DeprecationWarning: 'U' mode is deprecated
  with open(otu_file, 'rU') as f1:
FunGuild v1.0 Beta
Connecting with FUNGuild database ...
Traceback (most recent call last):
  File "Guilds_v1.1.py", line 128, in <module>
    current_record = json.loads(record)
  File "/Users/stewartlab/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/stewartlab/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/stewartlab/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Am I doing something wrong? Any help will be appreciated.
Thank you,

Jorge

**Comment by ZeweiSong** [comment]
Please check #38 for the solution.
