### ISSUE TITLE
Something wrong and Guild script do not work properly  

### ISSUE THREAD

**Issue by Linlt** [UMNFuN/FUNGuild#40]
when upload the example .txt file, it takes 8 hours and do not return a result (python 2.7).   
litaolindeMacBook-Pro:FUNGuild模版 litao.lin$ python bin/FUNGuild-master/Guilds_v1.0.py  -otu 
otu_table_example.txt 
FunGuild v1.0 Beta
Downloading fungi database ...

In this morning,
litaolindeMacBook-Pro:FUNGuild模版 litao.lin$ python bin/FUNGuild-master/Guilds_v1.0.py  -otu otu_table_example2.txt -db fungi
FunGuild v1.0 Beta
Downloading fungi database ...
Traceback (most recent call last):
  File "bin/FUNGuild-master/Guilds_v1.0.py", line 147, in <module>
    current = ast.literal_eval(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
 "taxon":"Aabaarnia siphulicola","guid":"1214B0D5-C087-429A-ADD0-396A8CA30CF2","mbNumber":"810084","taxonomicLevel":"20","trophicMode":"Pathotroph","guild":"Lichen Parasite","confidenceRanking":"Highly Probable","growthForm":"Microfungus","trait":"NULL","notes": .... et al.
SyntaxError: invalid syntax  

Another man run the Guild_1.1.py, jack-tristan$ python3  Guilds_v1.1.py  -otu rep_set_tax_assignments.txt 
FunGuild v1.1 Beta
Connecting with FUNGuild database ...  (from yesterday 10 p.m. to today 7 a.m.)

**Comment by ZeweiSong** [comment]
Can you try to use the v1.1 script? Take a look at issue #38

**Comment by Linlt** [comment]
litaolindeMacBook-Pro:FUNGuild模版 litao.lin$ python bin/FUNGuild-master/Guilds_v1.1.py  -otu otu_table_example2.txt -db fungi
FunGuild v1.1 Beta
Traceback (most recent call last):
  File "bin/FUNGuild-master/Guilds_v1.1.py", line 119, in <module>
    import requests
ImportError: No module named requests

**Comment by ZeweiSong** [comment]
It means that you don’t have the module named requests in your Python environment.

Can you check your Python version first? In general, we recommend Anaconda Python 3 distribute for biologist.

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Linlt** [comment]
litaolindeMacBook-Pro:FUNGuild模版 litao.lin$ python bin/FUNGuild-master/Guilds_v1.1.py  -otu otu_table_example2.txt -db fungi

FunGuild v1.1 Beta

Traceback (most recent call last):

  File "bin/FUNGuild-master/Guilds_v1.1.py", line 119, in <module>

    import requests

ImportError: No module named requests










At 2020-12-17 10:16:40, "Zewei Song" <notifications@github.com> wrote:

Can you try to use the v1.1 script? Take a look at issue #38

**Comment by ZeweiSong** [comment]
Take a look at this page:

https://requests.readthedocs.io/en/master/user/install/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
