### ISSUE TITLE
Error with running funguild code

### ISSUE THREAD

**Issue by janelucas** [UMNFuN/FUNGuild#48]
Hi,

I have been able to successfully run FUNGuild multiple times before, but this time I am having an error. 

I have run the code below, and also tried running it with the  Guilds v1.0.py and neither is working. I have python version 3.8.2. 

Any help would be greatly appreciated. 

-Jane

Janes-MBP:FUNGuild_katelyn janelucas$ python Guilds_v1.1.py -otu Katelyn_ITS_funguild.txt 

Guilds_v1.1.py:92: DeprecationWarning: 'U' mode is deprecated
  with open(otu_file, 'rU') as f1:
FunGuild v1.0 Beta
Connecting with FUNGuild database ...
Traceback (most recent call last):
  File "Guilds_v1.1.py", line 128, in <module>
    current_record = json.loads(record)
  File "/Users/janelucas/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/janelucas/opt/anaconda3/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 436 (char 435)

**Comment by XrandallX** [comment]
Hello, Did you manage to fix this issue? I am currently encountering the same thing and wondered if you could help?
Thanks, 
Kate

**Comment by XrandallX** [comment]
FYI - my similar errors all related to the formatting of the OTU table. 
The downloaded example was slightly wrong. 
OTU ID header should not include a space. 
I got confused from the Troubleshooting guide because it says to copy and paste into Excel and all fields should be in columns, but this didn't work for me. When I went back to continue reading through this webpage https://labs.cd2h.org/gitforager/repository/repository.jsp?id=30735845 , the 1st column should contain OTU_IT(tab)sample1(tab)sample2 etc.... so really shouldn't all sit in a tabulated form.
I also removed the gunk before the taxonomy list such as the percentage information and the parts including the | I worked on this in notepad rather than excel this time and it worked using the example otu_table.txt after my formatting changes. I also run this again with the abundance/samples removed and it still ran. 
I did this as I read that a large table can cause issues, so I was playing about with trying to reduce the size.... 
I will try to run my actual OTU table now following this method. 
The output however is messy and not easy to reformat. I will try work on this.
