### ISSUE TITLE
Keyerror: taxonomy

### ISSUE THREAD

**Issue by maracashay** [UMNFuN/FUNGuild#56]
Hi everyone,

I am working with an ASV table from dada2 output in R. I did some data wrangling to make a 'taxonomy' column as similar as I could to the example asv table provided. I also changed 'ASV' to 'OTU' in case that was important. The taxonomy column in the ASV table looks like this:

\|Vishniacozyma_victoriae\|k__Fungi;p__Basidiomycota;c__Tremellomycetes;o__Tremellales;f__Bulleribasidiaceae;g__Vishniacozyma;s__victoriae
--

Here is the error message: FUNGuild % python FUNGuild.py taxa -otu /Users/maraslaptop/Downloads/Fungal-Steam-ASV-Table.txt -format tsv -column taxonomy -classifier unite
Taxa parser initiated.
Loading OTU table: /Users/maraslaptop/Downloads/Fungal-Steam-ASV-Table.txt
Table format: tsv
Taxonomic column: taxonomy
Taxonomic style: unite
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'taxonomy'

I'm attaching a shortened version of my asv file. 
[Fungal-ASV-Funguild.txt](https://github.com/UMNFuN/FUNGuild/files/6352632/Fungal-ASV-Funguild.txt)

**Comment by sandipansamaddar** [comment]
Hi,
I am trying to format the dada2 ASV table to a format which is supported by FUNGuild but I am unable to do it. Can you please help me with that? I can also try after that to see if I get same error while running FUNGuild.

Thanks,

Sandipan

**Comment by ZeweiSong** [comment]
Can you specify the error you encountered? Please also provide with us the format you are using.

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sandipansamaddar** [comment]
Hi Zewei,
I didnot try funguild yet. I just outputted the ASV table (attached) from dada2 and want to format it as an input for Funguild. So I am wondering can I get some help on how to format a normal ASV table to a funguild format? After I have that file I will try Funguild and can let you know fi that works. 

Thanks and any help will be appreciated. 

Thanks again.
[dada2ASVtable.xlsx](https://github.com/UMNFuN/FUNGuild/files/6711640/dada2ASVtable.xlsx)


Sandipan

**Comment by ZeweiSong** [comment]
There is an example table file in the “example/” folder for your reference. Take a look and make sure your taxonomic string is in the right format (usually we follow UNITE).

Cheers,

Zewei

--
宋泽伟 Zewei Song
华大生命科学研究院 宏基因组研究所
BGI-Shenzhen Institute of Metagenomics
电话 Tel: +86 13632929180
邮件 Email: ***@***.***
邮件 Email: ***@***.***

发件人: Sandipan ***@***.***>
发送时间: Friday, June 25, 2021 3:20 AM
收件人: ***@***.***>
抄送: Zewei ***@***.***>; ***@***.***>
主题: Re: [UMNFuN/FUNGuild] Keyerror: taxonomy (#56)


Hi Zewei,
I didnot try funguild yet. I just outputted the ASV table (attached) from dada2 and want to format it as an input for Funguild. So I am wondering can I get some help on how to format a normal ASV table to a funguild format? After I have that file I will try Funguild and can let you know fi that works.

Thanks and any help will be appreciated.

Thanks again.
dada2ASVtable.xlsx<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Ffiles%2F6711640%2Fdada2ASVtable.xlsx&data=04%7C01%7C%7Cb0f21eaf2c1f4983b36b08d937450e12%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637601591993297036%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yoww57SRG%2BzLT3Izm44nPBp0XECE%2FdI2lBKI7Stttro%3D&reserved=0>

Sandipan

―

**Comment by merytouceda** [comment]
Hi! I had the same error as @maracashay here. Did anyone find a solution to it?
