### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by LenkaHar** [UMNFuN/FUNGuild#63]
Hi,
I run the script from Anaconda3 prompt and when I get to the guild assignment part I get a SSL certificate verification error. I have zero experience with python and didn’t find any working solution online. Do you have any advice? Thanks
Lenka

**Comment by ZeweiSong** [comment]
Hi, Lenka

Can you copy and paste the error mesage you got on the screen here? That will help us figure out what goes wrong.

Cheers,

Zewei

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________
From: LenkaHar ***@***.***>
Sent: Thursday, January 6, 2022 6:11:33 AM
To: UMNFuN/FUNGuild ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UMNFuN/FUNGuild] SSL certificate error (Issue #63)


Hi,
I run the script from Anaconda3 prompt and when I get to the guild assignment part I get a SSL certificate verification error. I have zero experience with python and didn’t find any working solution online. Do you have any advice? Thanks
Lenka

―
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Fissues%2F63&data=04%7C01%7C%7C6f8bb6d3db6443c73c5f08d9d09855d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770174962302160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F%2Bi1u8uHhQKY0KF1%2B36bau3Sp4cSZKDxgZLW8Zqm1hM%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3EDW7CL6T72NWRTU5522TUUS6ZLANCNFSM5LK6QAKA&data=04%7C01%7C%7C6f8bb6d3db6443c73c5f08d9d09855d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770174962302160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2vH%2F5daXuhHxy8lfmMnTWSn7jgVPwKnC88dKxYqs8Yk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C6f8bb6d3db6443c73c5f08d9d09855d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770174962302160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MqsGcXTJqyVnMzIa%2BRnJWiMDptgFCrdTjxWoeO7DJWk%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C6f8bb6d3db6443c73c5f08d9d09855d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770174962302160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pUwZEDhL1qfSQmhXDqsClpu46yCVfXJVR2nt3%2BxpeYo%3D&reserved=0>.

**Comment by LenkaHar** [comment]
Sure, here it is:

(base) C:\FUNGuild>python FUNGuild.py guild -taxa example/otu_table.taxa.txt
Guild parser initiated
Loading taxa file: example/otu_table.taxa.txt
Connecting with FUNGuild database ...
Traceback (most recent call last):
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\haranl\Anaconda3\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\haranl\Anaconda3\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\haranl\Anaconda3\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\haranl\Anaconda3\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\haranl\Anaconda3\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\haranl\Anaconda3\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\haranl\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\haranl\Anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\haranl\Anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\FUNGuild\FUNGuild.py", line 237, in <module>
    guild_parser(taxa)
  File "C:\FUNGuild\FUNGuild.py", line 158, in guild_parser
    db_content = json.load(urlopen(url + '&pp=1'))
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\haranl\Anaconda3\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

Cheers,
Lenka

**Comment by ZeweiSong** [comment]
It seems you are having a bad connection to the database. Can you check your internet condition?

Cheers,

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by LenkaHar** [comment]
How do you mean? The internet seems to be running fine.
Cheers
Lenka

**Comment by NatPombubpa** [comment]
I got a similar error. Is there any issue with the database currently? I tried FUNGuild on 2 different systems and both have problems while connecting to FUNGuild database.

Best,
Nat

**Comment by NatPombubpa** [comment]
FYI, I was able to fix database connection issue by changing line #148 of FUNGuild.py to url = 'https://www.mycoportal.org/fdex/services/api/db_return.php?dbReturn=Yes'

just need to add www. before mycoportal.org

@LenkaHar I'm not sure if this is the same issue, but you can try.

**Comment by christiansmith34** [comment]
> FYI, I was able to fix database connection issue by changing line #148 of FUNGuild.py to url = 'https://www.mycoportal.org/fdex/services/api/db_return.php?dbReturn=Yes'
> 
> just need to add [www](http://www). before mycoportal.org
> 
> @LenkaHar I'm not sure if this is the same issue, but you can try.

Was this able to fix the author's issue? I am having a nearly identical issue and updating the url in line 148 did not seem to fix the problem for me.

**Comment by merytouceda** [comment]
> > FYI, I was able to fix database connection issue by changing line #148 of FUNGuild.py to url = 'https://www.mycoportal.org/fdex/services/api/db_return.php?dbReturn=Yes'
> > just need to add [www](http://www). before mycoportal.org
> > @LenkaHar I'm not sure if this is the same issue, but you can try.
> 
> Was this able to fix the author's issue? I am having a nearly identical issue and updating the url in line 148 did not seem to fix the problem for me.

Same for me. Are there any other options to solve this issue?
